### ISSUE TITLE
cannot run in macos sierra

### ISSUE THREAD

**Issue by hanselke** [MayGo/tockler#10]
![screen shot 2017-06-20 at 7 16 54 pm](https://user-images.githubusercontent.com/1612565/27330690-181076f8-55ed-11e7-9e69-e4df1b751849.png)

**Comment by MayGo** [comment]
Working on a fix.

**Comment by MayGo** [comment]
There was problems with camelcase file names. Thats fixed in 3.0.4. Can you try that release?
