### ISSUE TITLE
Can not grant access to tockler for accessibility on Mac

### ISSUE THREAD

**Issue by ammarrush** [MayGo/tockler#109]
I am trying to develop the app on Mac, when I run `yarn start` the app tries to open but is blocked because it asks for accessibility permission when I go to accessibility to allow app the permission I do not see the app there so I am not able to allow it access.

**Comment by MayGo** [comment]
Depending on where you run the app. If you run from VS Code terminal then you should allow VS Code from the list. If you run directly from the terminal, then select terminal. If those items are not on the list, then press + in the list and navigate to applications/VSCode.app or Applications/Utilities/Console.app. Perhaps drag-drop works also.

**Comment by ammarrush** [comment]
Ok that worked thanks!

**Comment by MayGo** [comment]
you're welcome
