### ISSUE TITLE
3.19.7 Mac Menu Bar Icon blank

### ISSUE THREAD

**Issue by big610** [MayGo/tockler#157]
Hello Maigo,
You've been perfect Catalina, Big Sur, thanks for your labor and excellent work.
3.19.0 did not alert for update to 3.19.7.
3.19.7 in the Menu Bar, the icon position is there, but your coloring came out blank, no purple. You'll see the position whited out, to click on & the blank position space.

**Comment by MayGo** [comment]
It should check for updates once a day. Perhaps in some cases, it can take longer.
App had a bug with "exit & install" and that is fixed now.
Made icon white like most of the apps in macOS have. 
Should look like this:

<img width="125" alt="Screenshot 2021-07-16 at 22 50 33" src="https://user-images.githubusercontent.com/1929299/126001612-95f94b41-61c1-42b6-b81f-cda444895b6f.png">

Let me know if you see anything else. Or have other opinions about white icon :)

**Comment by big610** [comment]
Your in Dark Mode. I'm in Light Mode, I can't see it as White, until I click on it. The white won't display. 
Needs to go back to Purple. White is a no for Light Mode, can't see under the light blue with Catalina. Black I don't like because it blends in with all of Apples Black.
![Tockler White](https://user-images.githubusercontent.com/35133409/126002665-a4e402fa-9689-4acc-98d8-3b11905b2389.png)

**Comment by MayGo** [comment]
I was also in light mode. For me, it actually depends on a desktop background color. I made a fix, so the icon color will change between black and white.
Will be fixed in 3.19.7 ~ 1 hour

**Comment by big610** [comment]
I hope you can retain Purple, that's what made & distinguished your app from not a clone to Apple's black.
Much easier to see as Purple versus everyone else mostly Black.

**Comment by MayGo** [comment]
I hear you. Let me keep it, for now, perhaps I will change it back if it does not feel right.
Perhaps I can add this to Settings, purple or black/white.

**Comment by big610** [comment]
Hope you choose to implement Purple in settings.
It has been an honor for me to educate other devs, your App stands out not being Apple Black, you don't listen to Apple or get paid by Apple.

**Comment by MayGo** [comment]
@big610 In 3.19.10 you can now show purple icon in settings:
![Jul-19-2021 19-14-38small](https://user-images.githubusercontent.com/1929299/126193115-30bc4bb6-77b4-40af-961d-34606ee91023.gif)
Thanks for your support!

**Comment by MayGo** [comment]
@big610 added Windows Portable version in 3.19.11
https://github.com/MayGo/tockler/releases/tag/v3.19.11
