### ISSUE TITLE
Task Modification broken in new View

### ISSUE THREAD

**Issue by kown7** [MayGo/tockler#164]
With the new UI I seem to be unable to modify the duration of a task.

Version: probably latest.

**Comment by MayGo** [comment]
You should be able to click on task item. And change the time with input. And also with dragging timeline brush.
![Aug-11-2021 13-07-27low](https://user-images.githubusercontent.com/1929299/129011150-17c39485-5448-4a3f-b60c-6da3707c1b8b.gif)


Just in case check your version.
In About Tockler:
<img width="259" alt="Screenshot 2021-08-11 at 13 08 59" src="https://user-images.githubusercontent.com/1929299/129011426-f31ef851-f311-4051-9553-e671c8e8d3e0.png">

<img width="290" alt="Screenshot 2021-08-11 at 13 09 07" src="https://user-images.githubusercontent.com/1929299/129011446-6b584a3a-cd9a-4ee7-96bd-1371c8ca8a73.png">

**Comment by kown7** [comment]
So far it works, but clicking `Update` doesn't update anything. It just goes gray. Windows specific problem? It feels that there are/were regression errors on the old UI. Could that be related?

That `About tockler` isn't available:

![grafik](https://user-images.githubusercontent.com/10778686/129015847-b3ff6f71-5e59-42ec-a7a7-31b81c51df36.png)

**Comment by kown7** [comment]
Version still not available under Windows and updater probably still not working either.

The reported problem is fixed in the latest version.
