### ISSUE TITLE
App Title Blank

### ISSUE THREAD

**Issue by kown7** [MayGo/tockler#193]
The latest release 3.21.11 doesn't track app usage anymore. Only Status (idle/online) is shown.

**Comment by MayGo** [comment]
What operating system/version?

**Comment by kown7** [comment]
Win10 19044

**Comment by IgnusG** [comment]
I have the same issue. I've tried both the portable and installed version both locally and for all accounts but no apps seem to be tracked.

Running on the 3.21.10 Tockler version on Windows 11 Home 21H2 OS Build 22000.469

**Comment by MayGo** [comment]
@IgnusG @kown7 
Can you try v3.21.12 ?

**Comment by kown7** [comment]
Works for me.

Now only #166 and #167 missing 😋

**Comment by MayGo** [comment]
Thanks for reporting it. Will add those tickets to what-to-do-next-if-have-spare-time-and-motivation list. 😀

**Comment by kown7** [comment]
If everyone shares that pile, it's so big it must've collapsed into to a black hole. Which would explain a thing or two 😉
