### ISSUE TITLE
 Argument of type '"activate-with-no-open-windows"' is not assignable to parameter of type '"window-all-closed"'.

### ISSUE THREAD

**Issue by hanselke** [MayGo/tockler#20]
so i did rm -rf node_modules
yarn install --ignore-optional
nps run

[main] ERROR in [at-loader] ./app/index.ts:89:8 
[main]     TS2345: Argument of type '"activate-with-no-open-windows"' is not assignable to parameter of type '"window-all-closed"'.

doing electron-builder, then running the app gives you a blank screen

**Comment by MayGo** [comment]
Event activate-with-no-open-windows is deprecated in newer electron ( 1.6.11). 
Fixed by replacing with correct event: 'activate'
