### ISSUE TITLE
Is it possible to change the idle detection time?

### ISSUE THREAD

**Issue by LukasPoque** [MayGo/tockler#230]
Sometimes Tocker detects my idle time way too fast, for example while I'm reading a text. Is it possible to change the detection time to 3 or 5 minutes before idle is detected?

BTW: very nice project 🚀

**Comment by MayGo** [comment]
Thanks!

I can add a field to Settings. Currently, it is 1 minute.
But I am not sure when I can do it. And my Apple Developer program membership expired. Not sure when I am willing to spend money on that again. 
Are you on Mac or Windows?

**Comment by LukasPoque** [comment]
Yeah, a new setting field would be great :) 

I'm sorry to hear that your Apple Developer program membership is expired :/ I'm on Windows, so for me there is no special need for a new apple version release but for the whole project it would be nice.

**Comment by LukasPoque** [comment]
Any updates on this feature for windows? 👀

**Comment by MayGo** [comment]
I feel in my bones, that I will work on a bunch of Tockler tickets soon  😉

**Comment by MayGo** [comment]
It is fixed in https://github.com/MayGo/tockler/releases/tag/v3.21.14

**Comment by LukasPoque** [comment]
Thank you very mutch🚀 I'm going to test the feature and close this issue if everything works correct.

**Comment by LukasPoque** [comment]
Works seamlessly, thank you very much :)
