### ISSUE TITLE
Can you please share the documentation of the Code

### ISSUE THREAD

**Issue by Engr-Talha** [MayGo/tockler#265]
Hello Devs,  First of all, thanks for making the source code open to all devs, , I am working on the project management tool just like Jira and had seen your tool for time tracking and screen monitoring, would you please share the documentation so that I could use the code in my app. So if you could help me.

Thanks

**Comment by MayGo** [comment]
Hi, no devs, only me. And no docs.

**Comment by isaiah2004** [comment]
> Hi, no devs, only me. And no docs.

Respect
