### ISSUE TITLE
[Question] Restore TrackItems from DB after reinstall the hole machine

### ISSUE THREAD

**Issue by lemrm** [MayGo/tockler#277]
If I have new installation. Can I get back the history of all the tracked items for all the days from the former db file?

**Comment by MayGo** [comment]
On MacOS the DB file is located in /Users/<UserName>/Library/Application Support/tockler/tracker.db
On Windows it should be equivalent "userData" directory

**Comment by lemrm** [comment]
Ok, I tried this. Then I got a white empty window. DB file maybe have a problem. Tracked items should be 130000, but I only can view up tu entry 31121.

**Comment by lemrm** [comment]
I got this error

```
Error invoking remote method 'DB_EXECUTE_QUERY': Error: SQLITE_CORRUPT: database disk image is malformed
```

**Comment by lemrm** [comment]
Solved -> [Link](https://www.sqlite.org/recovery.html)
