### ISSUE TITLE
Uncaught exception: please install sqlite3 manunally

### ISSUE THREAD

**Issue by hanselke** [MayGo/tockler#28]
Uncaught Exception:
Error: Please install sqlite3 package manually
    at new ConnectionManager (/Applications/Tockler.app/Contents/Resources/app/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25:13)
    at new SqliteDialect (/Applications/Tockler.app/Contents/Resources/app/node_modules/sequelize/lib/dialects/sqlite/index.js:12:28)
    at new Sequelize (/Applications/Tockler.app/Contents/Resources/app/node_modules/sequelize/lib/sequelize.js:233:18)
    at new Database (eval at <anonymous> (/Applications/Tockler.app/Contents/Resources/app/dist/index.js:137:1), <anonymous>:18:31)
    at eval (eval at <anonymous> (/Applications/Tockler.app/Contents/Resources/app/dist/index.js:137:1), <anonymous>:49:18)
    at Object.<anonymous> (/Applications/Tockler.app/Contents/Resources/app/dist/index.js:137:1)
    at __webpack_require__ (/Applications/Tockler.app/Contents/Resources/app/dist/index.js:20:30)
    at eval (eval at <anonymous> (/Applications/Tockler.app/Contents/Resources/app/dist/index.js:103:1), <anonymous>:12:17)
    at Object.<anonymous> (/Applications/Tockler.app/Contents/Resources/app/dist/index.js:103:1)
    at __webpack_require__ (/Applications/Tockler.app/Contents/Resources/app/dist/index.js:20:30)
    at eval (eval at <anonymous> (/Applications/Tockler.app/Contents/Resources/app/dist/index.js:207:1), <anonymous>:11:30)
    at Object.<anonymous> (/Applications/Tockler.app/Contents/Resources/app/dist/index.js:207:1)
    at __webpack_require__ (/Applications/Tockler.app/Contents/Resources/app/dist/index.js:20:30)
    at eval (eval at <anonymous> (/Applications/Tockler.app/Contents/Resources/app/dist/index.js:313:1), <anonymous>:3:28)
    at Object.<anonymous> (/Applications/Tockler.app/Contents/Resources/app/dist/index.js:313:1)
    at __webpack_require__ (/Applications/Tockler.app/Contents/Resources/app/dist/index.js:20:30)

tried doing yarn install --force and installing sqlite3 globally via npm install -g, still same error

**Comment by MayGo** [comment]
tried from master branch
removed node_modules
then
`yarn`
`nps run`

no errors.

Try removing yarn.lock before installing dependencies.

**Comment by hanselke** [comment]
hi

tried that, doesnt work. still get the same error.

do you think you could list your globally installed npm packages?

npm list -g --depth=0

**Comment by MayGo** [comment]
├── electron-packager@5.2.0
├── jest@20.0.4
├── jest-cli@0.8.2    
├── n@2.1.5
├── node-gyp@3.4.0
├── node-inspector@0.12.5
├── npm@3.10.10
├── npm-check@5.4.0
├── npm-check-updates@2.7.1
├── nps@5.3.1
├── nw-gyp@0.13.0
├── requirejs@2.3.3
├── sqlite3@3.1.4
├── tslint@5.3.2
├── typescript@2.4.0
├── typings@2.1.0
├── UNMET PEER DEPENDENCY webpack@>=1.3.0 <3
├── webpack-dev-server@1.15.1
├── webpack-init@0.1.1
└── yarn@0.24.5

**Comment by MayGo** [comment]
Global packages shouldn't affect anything. appveyor and travis builds have no global dependencies.
What environment you have (os, node, npm)

**Comment by MayGo** [comment]
I tried with node 8. Worked the same.

**Comment by hanselke** [comment]
mm seems like it might be related to https://web.archive.org/web/20160318170558/http://verysimple.com:80/2015/05/30/using-node_sqlite3-with-electron/

Tried rebuilding with that link and it didnt work.


OS: MacOS Sierra 10.12.5 (16F73)
node: v8.1.2

├── bitbucket-issue-manager@1.0.8
├── bower@1.8.0
├── electron@1.6.11
├── electron-builder@19.5.1
├── electron-packager@8.7.2
├── email-verify@0.1.1
├── generator-hubot@0.4.0
├── generator-seneca@0.0.1
├── gulp@3.9.1
├── http-server@0.10.0
├── local-npm@2.0.1
├── make@0.8.1
├── marked@0.3.6
├── mern-cli@3.0.1
├── nan@2.6.2
├── nativefier@7.4.0
├── node-gyp@3.6.2
├── node-red@0.17.0
├── node-red-contrib-chatbot@0.7.3
├── node-red-dashboard@2.4.1
├── npm@5.0.3
├── npmrc@1.1.1
├── nps@5.3.2
├── nw-gyp@3.4.0
├── pakmanager@0.12.1
├── phantomjs@2.1.7
├── pm2@2.5.0
├── react@15.6.1
├── react-init@0.0.1
├── saas@1.0.0
├── sqlite3@3.1.8
├── testcafe@0.16.2
├── webpack@3.0.0
├── yarn@0.24.5
└── yo@2.0.0

**Comment by MayGo** [comment]
I have same OS and node version.

when doing "yarn", you get "rebuilding" lines?
```
electron-builder 19.12.0
Using electron-builder.yml configuration file
Rebuilding native production dependencies for darwin:x64
Rebuilding native dependency sqlite3
Rebuilding native dependency ref
Rebuilding native dependency iconv
Rebuilding native dependency ffi
```

try cleaning everything:
yarn cache clean
rm -rf node_modules/

**Comment by hanselke** [comment]
arrrgh. still the same problem. 

yarn
yarn install v0.24.5
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning electron-rebuild > fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
warning electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0: 
[2/4] 🚚  Fetching packages...
warning 7zip-bin-win@2.1.0: The platform "darwin" is incompatible with this module.
info "7zip-bin-win@2.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
warning 7zip-bin-linux@1.1.0: The platform "darwin" is incompatible with this module.
info "7zip-bin-linux@1.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
$ electron-builder install-app-deps
electron-builder 19.12.0
Using electron-builder.yml configuration file
Rebuilding native production dependencies for darwin:x64
Rebuilding native dependency sqlite3
Rebuilding native dependency ref
Rebuilding native dependency iconv
Rebuilding native dependency ffi
✨  Done in 672.09s.
Hansels-MacBook-Air:tockler hanselke$  nps run
nps is executing `run`: node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold,bgGreen.bold" --prefix "[{name}]" --names "clean,main,renderer" 'nps clean' 'nps main' 'nps renderer'
[clean] nps is executing `clean`: node node_modules/rimraf/bin.js dist
[renderer] nps is executing `renderer`: nps renderer.build.dev
[main] nps is executing `main`: nps main.build.dev && nps main.run
[clean] nps clean exited with code 0
[main] nps is executing `main.build.dev`: webpack --config webpack.config.main.js -d
[renderer] nps is executing `renderer.build.dev`: webpack --watch -d
[main] Using tsOptions: { configFileName: '/Users/hanselke/Dev/tockler/app/tsconfig.main.json' }
[main] 
[main] [at-loader] Using typescript@2.4.1 from typescript and "tsconfig.json" from /Users/hanselke/Dev/tockler/app/tsconfig.main.json.
[main] 
[renderer] 
[renderer] Webpack is watching the files…
[renderer] 
[renderer] 
[renderer] [at-loader] Using typescript@2.4.1 from typescript and "tsconfig.json" from /Users/hanselke/Dev/tockler/tsconfig.json (in a forked process).
[renderer] 
[main] 
[main] [at-loader] Checking started in a separate process...
[main] 
[main] [at-loader] Ok, 0.006 sec.
[main]  DONE  Compiled successfully in 13634ms9:07:05 PM
[main] 
[main] Hash: 10f46a1ef070a0685e64
[main] Version: webpack 2.6.1
[main] Time: 13634ms
[main]    Asset    Size  Chunks             Chunk Names
[main] index.js  183 kB       0  [emitted]  index
[main]    [0] ./app/log-manager.ts 386 bytes {0} [built]
[main]    [1] ./app/config.ts 998 bytes {0} [built]
[main]    [3] ./app/state-manager.ts 6.99 kB {0} [built]
[main]    [4] ./app/background-utils.ts 2.88 kB {0} [built]
[main]    [5] ./app/enums/track-item-type.ts 369 bytes {0} [built]
[main]    [6] ./app/services/settings-service.ts 2.74 kB {0} [built]
[main]    [7] ./app/background-service.ts 4.66 kB {0} [built]
[main]   [14] ./app/app-constants.ts 302 bytes {0} [built]
[main]   [16] ./app/services/app-setting-service.ts 4.2 kB {0} [built]
[main]   [19] ./app/app-manager.ts 1.8 kB {0} [built]
[main]   [20] ./app/app-updater.ts 1.96 kB {0} [built]
[main]   [21] ./app/background-job.ts 1.06 kB {0} [built]
[main]   [22] ./app/window-manager.ts 3.37 kB {0} [built]
[main]   [26] ./app/index.ts 3.15 kB {0} [built]
[main]   [29] ./app/jobs/status-track-item-job.ts 3.88 kB {0} [built]
[main]     + 29 hidden modules
[main] nps is executing `main.run`: cross-env NODE_ENV=development electron ./dist
[main] App threw an error during load
[main] Error: Please install sqlite3 package manually
[main]     at new ConnectionManager (/Users/hanselke/Dev/tockler/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25:13)
[main]     at new SqliteDialect (/Users/hanselke/Dev/tockler/node_modules/sequelize/lib/dialects/sqlite/index.js:12:28)
[main]     at new Sequelize (/Users/hanselke/Dev/tockler/node_modules/sequelize/lib/sequelize.js:233:18)
[main]     at new Database (eval at <anonymous> (/Users/hanselke/Dev/tockler/dist/index.js:186:1), <anonymous>:18:31)
[main]     at eval (eval at <anonymous> (/Users/hanselke/Dev/tockler/dist/index.js:186:1), <anonymous>:49:18)
[main]     at Object.<anonymous> (/Users/hanselke/Dev/tockler/dist/index.js:186:1)
[main]     at __webpack_require__ (/Users/hanselke/Dev/tockler/dist/index.js:20:30)
[main]     at eval (eval at <anonymous> (/Users/hanselke/Dev/tockler/dist/index.js:198:1), <anonymous>:12:17)
[main]     at Object.<anonymous> (/Users/hanselke/Dev/tockler/dist/index.js:198:1)
[main]     at __webpack_require__ (/Users/hanselke/Dev/tockler/dist/index.js:20:30)
[main]     at eval (eval at <anonymous> (/Users/hanselke/Dev/tockler/dist/index.js:114:1), <anonymous>:15:30)
[main]     at Object.<anonymous> (/Users/hanselke/Dev/tockler/dist/index.js:114:1)
[main]     at __webpack_require__ (/Users/hanselke/Dev/tockler/dist/index.js:20:30)
[main]     at eval (eval at <anonymous> (/Users/hanselke/Dev/tockler/dist/index.js:406:1), <anonymous>:12:25)
[main]     at Object.<anonymous> (/Users/hanselke/Dev/tockler/dist/index.js:406:1)
[main]     at __webpack_require__ (/Users/hanselke/Dev/tockler/dist/index.js:20:30)

**Comment by MayGo** [comment]
you can try: 
`electron-rebuild -v 1.6.11 -f -w sqlite3`
I tried it, but it had errors, no time to debug that.

Have you tried to make "clean" clone of repo?

**Comment by hanselke** [comment]
no luck. still same problem.
