### ISSUE TITLE
Can you please explain how i compile you code 

### ISSUE THREAD

**Issue by singhshakti1999** [MayGo/tockler#280]

**Comment by MayGo** [comment]
From readme:

Start application
Renderer and main process builds have been separated. It's easier to boilerplate this project and switch client framework.

React client (renderer)
cd client/
yarn install            # Install dependencies
yarn start
Electron (main)
cd electron/
yarn install            # Install dependencies
yarn start

Build scripts samples are in travis/appveyor files.
