### ISSUE TITLE
Manual refresh button

### ISSUE THREAD

**Issue by herrbrixter** [MayGo/tockler#286]
Is there a manual refresh button? I think the statistics refresh automatically but I don't know what triggers it. Sometimes I use the statistics on the screen but they are actually not up to date.

I'd like to have a manual refresh button so that I have more confidence that the data I see on screen are the latest data. I don't mind if I have to manually click the refresh button.

**Comment by MayGo** [comment]
<img width="331" alt="Screenshot 2024-11-12 at 14 56 02" src="https://github.com/user-attachments/assets/9f8b2363-ec32-42a5-8efe-1edf50691f02">
