### ISSUE TITLE
What are groups for?

### ISSUE THREAD

**Issue by hanselke** [MayGo/tockler#36]
the latest mac binary works. thanks a lot!

so i have these line items in my timeline..

App: Title
Code: Visual Studio Code
Code: code.js -- nextactionmeteor
Google chrome: http://localhost:3000/blahblah

Code: code.js -- openbpass
Google Chrome: http://localhost:8000/blahblah

I would like to sort my time between projects.

What are Groups for? Can i create my own groups?

My timeline page also shows only 2 charts and there are blanks in another 2 sections, could those be for groups?

![screen shot 2017-08-13 at 12 06 45 pm](https://user-images.githubusercontent.com/1612565/29246067-03037cb2-8020-11e7-91fa-88209ed4fa26.png)

**Comment by MayGo** [comment]
It should only show 3 piecharts in a row: App usage, OS state, log items. Log items can be started in tray. You can manually log your work in tray view.
If there is some informative chart missing, you can do a pull-request or issue.
