### ISSUE TITLE
tockler.desktop does not pass desktop-file-validate

### ISSUE THREAD

**Issue by probonopd** [MayGo/tockler#37]
```
/mnt/tockler.desktop: error: value "Utility,;" for key "Categories" in group "Desktop Entry" contains an unregistered value "Utility,"; values extending the format should start with "X-"

/mnt/tockler.desktop: hint: value "Utility,;" for key "Categories" in group "Desktop Entry" does not contain a registered main category; application might only show up in a "catch-all" section of the application menu
```

Reference:
https://travis-ci.org/AppImage/AppImageHub/builds/266238319#L543-L544

Please upgrade to the latest version of electron-builder.

**Comment by MayGo** [comment]
should be fixed in latest release

**Comment by probonopd** [comment]
If anyone could be so kind to ping me once the next release is out, I'd be happy to add this app to AppImageHub, the central catalog of available AppImages.

**Comment by MayGo** [comment]
It was fixed with commit https://github.com/MayGo/tockler/commit/424b715c517f0530dc171ba9870cd8f842d57730
And is released: https://github.com/MayGo/tockler/releases/tag/v3.1.3
