### ISSUE TITLE
Opening apps gives the dreaded spinny wheel

### ISSUE THREAD

**Issue by saibotsivad** [MayGo/tockler#5]
### System

Mac OSX El Capitan.
Node: v6.2.1
npm: 3.10.5
Tockler: 2.1.0
### Recreate
- Tockler is running, and is visible in the taskbar.
- Fully quit an application, e.g. Safari or Sublime Text Editor.
- Re-open that application.
### What happens
- The application (e.g. Safari or Sublime Text Editor) hangs and is unresponsive. All other applications remain responsive.
### What I expect to happen
- Running Tockler should not cause an application to be unresponsive.

---

Where are the logs kept? Maybe they have some information.

**Comment by MayGo** [comment]
I havent experienced something like that, i look into that.
Logs are kept in user folder: /Users/myusername/Library/Application
Support/Tockler/

2016-10-12 7:26 GMT+03:00 Tobias Davis <notifications@github.com>:

**Comment by saibotsivad** [comment]
I didn't see anything that caught my eye in the `stdout.json`, but when the not-Tockler application was hanging, I would get a few of these entries:

```json
{
    "hostname": "Tobiass-MacBook-Air.local",
    "level": 50,
    "msg": "saveForegroundWindowTitle error: /Applications/Tockler.app/Contents/Resources/app/get-foreground-window-title.osa:255:260: execution error: System Events got an error: Can’t get window 1 of process \"Adium\". Invalid index. (-1719)\n",
    "name": "background-service",
    "pid": 33279,
    "time": "2016-10-13T00:27:58.803Z",
    "v": 0
}
```

And then a fair number of these:

```json
{
    "hostname": "Tobiass-MacBook-Air.local",
    "level": 20,
    "msg": "Found RUNNING_LOG_ITEM config:  Instance {\n  dataValues: \n   { id: 1,\n     name: 'RUNNING_LOG_ITEM',\n     jsonData: '{}',\n     createdAt: 2016-10-12T00:52:24.198Z,\n     updatedAt: 2016-10-12T00:52:24.198Z },\n  _previousDataValues: \n   { id: 1,\n     name: 'RUNNING_LOG_ITEM',\n     jsonData: '{}',\n     createdAt: 2016-10-12T00:52:24.198Z,\n     updatedAt: 2016-10-12T00:52:24.198Z },\n  _changed: {},\n  '$modelOptions': \n   { timestamps: true,\n     instanceMethods: {},\n     classMethods: {},\n     validate: {},\n     freezeTableName: false,\n     underscored: false,\n     underscoredAll: false,\n     paranoid: false,\n     rejectOnEmpty: false,\n     whereCollection: { name: 'RUNNING_LOG_ITEM' },\n     schema: null,\n     schemaDelimiter: '',\n     defaultScope: {},\n     scopes: [],\n     hooks: {},\n     indexes: [],\n     name: { plural: 'Settings', singular: 'Setting' },\n     omitNul: false,\n     sequelize: \n      Sequelize {\n        options: [Object],\n        config: [Object],\n        dialect: [Object],\n        models: [Object],\n        modelManager: [Object],\n        connectionManager: [Object],\n        importCache: {},\n        test: [Object],\n        queryInterface: [Object] },\n     uniqueKeys: {},\n     hasPrimaryKeys: true },\n  '$options': \n   { isNewRecord: false,\n     '$schema': null,\n     '$schemaDelimiter': '',\n     raw: true,\n     attributes: [ 'id', 'name', 'jsonData', 'createdAt', 'updatedAt' ] },\n  hasPrimaryKeys: true,\n  __eagerlyLoadedAssociations: [],\n  isNewRecord: false,\n  jsonDataParsed: {} }",
    "name": "background-service",
    "pid": 33279,
    "time": "2016-10-13T00:28:01.488Z",
    "v": 0
}
```

None of that looks particularly important, so I'm out of ideas for now.

I use Tockler on my work computer with no problems, but I guess I'll have to disable it on my personal computer until I have time to poke around more.

Thanks for any insight you can give, it's a very useful app!

**Comment by MayGo** [comment]
I upgrades all dependencies to latest. Try v2.2.0. I have couple of ideas, but i want to rule out other dependencies.

**Comment by saibotsivad** [comment]
Sorry for taking 2 months to respond 😄 I finally re-installed and am getting the same problem. Any ideas of things I can poke at to help figure it out?

**Comment by MayGo** [comment]
Made some fixes. Try v2.3.0. Changed osascript that reads active window title.

**Comment by saibotsivad** [comment]
It's still gives me the spinning wheel with 2.3.0 so I'll see if I can get it building locally and poke around with it. :man_shrugging:

**Comment by MayGo** [comment]
Can you provide new logs? There should not be any "Can’t get window 1 of
process" errors.

2017-01-16 23:30 GMT+02:00 Tobias Davis <notifications@github.com>:

**Comment by MayGo** [comment]
you can try v2.4.3

**Comment by MayGo** [comment]
Latest version (3.0.4) uses active-win plugin for getting active window names.

**Comment by saibotsivad** [comment]
With the installation of 3.0.4, I no longer have this problem.

Thanks so much for sticking with it! :heart:
