### ISSUE TITLE
macOS 10.15 Catalina

### ISSUE THREAD

**Issue by big610** [MayGo/tockler#60]
Catalina macOS 10.15 Tockler editions 3.4.13 and lower are not displaying any data, in addition missing an alert there is an update to a new version on both Catalina, and when I was on Mojave 10.14.

**Comment by big610** [comment]
Catalina macOS 10.15 Tockler 3.6.2 does not gather any data. Alert to update did not notify. System Preferences allowed both Accessibility & Full Disk Access.

**Comment by MayGo** [comment]
There might be a problem with connecting with sqlite database.
It does not collect even online/offline data?

**Comment by big610** [comment]
Thanks for fast response. Do you have a Mac? Catalina? Virtual? , etc.
Yes with 3.6.2 no data. Now I am nicely taking your automatic update from 3.6.2.
Hang on, will give you an edit of what happens. One idea I could swap out the sqlite  to make it easier if you give me one, till we figure it out.

**Comment by MayGo** [comment]
I have Catalina macOs, same as you.
I fixed problem with database syncing, can you try v3.6.4? Manually. I will check update problems.
And thanks for submitting issues.

**Comment by big610** [comment]
Thanks for your dedication to resolve.
Tockler 3.6.4 is the first macOS Catalina working version.
Installed Manual per your directions. Data is appearing. 

System Preferences/Security & Privacy/Privacy  What do we need checked? 
Screen Recording? Full Disk Access? Accessibility?

I suggest you delete the old 3..1.5 from the initial page & update Release Change Notes to:
v3.6.4 fix database sync osMac 10.15 Catalina Compatible. 

I always like learning, what was the issue you had to overcome to fix in Catalina?

**Comment by MayGo** [comment]
Tockler needs Screen Recording and Accessibility checked.

Fix for Catalina was to upgrade https://github.com/sindresorhus/active-win but that was done at first 3.6.* version. What you had was database syncing problems, luckily that was fixed by changing `sequalize.sync` settings.
