### ISSUE TITLE
Update to 3.8.2

### ISSUE THREAD

**Issue by kown7** [MayGo/tockler#64]
Updating from 3.6.5 to 3.8.2 breaks with an exisiting database (Windows). It won't run with an exisiting folder.

**Comment by MayGo** [comment]
I am looking into that.

**Comment by kown7** [comment]
Thank you.

It also complains about 3.8.3 update not being available.

**Comment by MayGo** [comment]
Should be fixed in 3.9.2.
3.8.3 update not being available -  it was because there was a release by that name, but i removed exe from that.
