### ISSUE TITLE
Tockler does not register anything

### ISSUE THREAD

**Issue by Luukgr** [MayGo/tockler#66]
Tockler 3.9.3
Kubuntu 19.10
Installed as deb package

**Comment by MayGo** [comment]
Can you share some of the logs from ~/.config/tockler/logs/main.log
There might be some errors.

**Comment by Luukgr** [comment]
`[2020-02-15 15:43:57.992] [error] App errored in ready event: {
  constructor: 'DatabaseError',
  name: 'SequelizeDatabaseError',
  parent: {
    constructor: 'Error',
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: "SELECT `id`, `name`, `jsonData` FROM `Settings` AS `a` WHERE `a`.`name` = 'RUNNING_LOG_ITEM' LIMIT 1;",
    stack: 'Error: SQLITE_ERROR: no such table: Settings'
  },
  original: {
    constructor: 'Error',
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: "SELECT `id`, `name`, `jsonData` FROM `Settings` AS `a` WHERE `a`.`name` = 'RUNNING_LOG_ITEM' LIMIT 1;",
    stack: 'Error: SQLITE_ERROR: no such table: Settings'
  },
  sql: "SELECT `id`, `name`, `jsonData` FROM `Settings` AS `a` WHERE `a`.`name` = 'RUNNING_LOG_ITEM' LIMIT 1;",
  stack: 'SequelizeDatabaseError: SQLITE_ERROR: no such table: Settings\n' +
    '    at Query.formatError (/opt/Tockler/resources/app/node_modules/sequelize/lib/dialects/sqlite/query.js:422:16)\n' +
    '    at Query._handleQueryResponse (/opt/Tockler/resources/app/node_modules/sequelize/lib/dialects/sqlite/query.js:73:18)\n' +
    '    at afterExecute (/opt/Tockler/resources/app/node_modules/sequelize/lib/dialects/sqlite/query.js:250:31)\n' +
    '    at replacement (/opt/Tockler/resources/app/node_modules/sqlite3/lib/trace.js:19:31)\n' +
    '    at Statement.errBack (/opt/Tockler/resources/app/node_modules/sqlite3/lib/sqlite3.js:16:21)'
}`

**Comment by MayGo** [comment]
thanks, i need to run Kubuntu VM to test.
Also, can you try v3.10.0?

**Comment by Keir3d** [comment]
I've been getting the same issue since 3.6.2 on windows. No tracked items.
3.4.13 tracks apps fine but I can't stop it from auto-updating.

**Comment by MayGo** [comment]
Thanks for feedback. I will try some things, to get this bug fixed. If it takes more than 2 days, i will fix 3.4.13, so auto-updating can be turned of at least.

**Comment by Luukgr** [comment]
> thanks, i need to run Kubuntu VM to test.
> Also, can you try v3.10.0?

v3.10.0 does not start. (same for 3.10.1)

**Comment by MayGo** [comment]
Can you try 3.11.7? I tested Kubuntu VM successfully

**Comment by Luukgr** [comment]
yes it works! Very nice.
