### ISSUE TITLE
phantom summary entries

### ISSUE THREAD

**Issue by phanirithvij** [MayGo/tockler#77]
![image](https://user-images.githubusercontent.com/29627898/81774099-7052b680-9507-11ea-998d-73e1cec4774e.png)

I first installed this on the 10th of this month but there are some entries in the calendar before that. Is there some kind of offset issue?

**Comment by MayGo** [comment]
If you click on those items: 01, 02, 03- it should take you to the timeline view. Then what is shown there?

**Comment by phanirithvij** [comment]
@MayGo I went and opened the summary page and it loads forever seems like a new bug.
[video](https://res.cloudinary.com/rootworld/video/upload/v1589613615/COupso6fpa.mp4)

**Comment by phanirithvij** [comment]
> If you click on those items: 01, 02, 03- it should take you to the timeline view. Then what is shown there?

I'm not able to open it now but I remember it showing empty timeline with 4 grey filled pie charts

**Comment by MayGo** [comment]
@phanirithvij  This is fixed in 3.14.1.

> I don't see tockler open, or even in the taskbar.
By default it should show tray icon, even when running development mode.
