### ISSUE TITLE
“Tockler” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by hanselke** [MayGo/tockler#78]
download mac dmg 3.14.2 from releases tab. installed it and cant run it.

**Comment by MayGo** [comment]
I think you should enable "App Store and Identified developers" from "Allow apps downloaded from"

https://support.apple.com/et-ee/HT202491

**Comment by tscpp** [comment]
It's apple-related, not an issue with Tockler itself.
