### ISSUE TITLE
[feature request] Dark Mode

### ISSUE THREAD

**Issue by NoodleSushi** [MayGo/tockler#81]
Really love this program, only problem is that there's no dark mode.

**Comment by MayGo** [comment]
thanks, will implement it soon.

**Comment by MayGo** [comment]
@NoodleSushi 
Added Dark Mode in v3.17.0.
Let me know if you see some errors or ideas for improvement.

**Comment by NoodleSushi** [comment]
Just what I asked for, thank you so much!
