### ISSUE TITLE
Can't start the dev server for client

### ISSUE THREAD

**Issue by ammarNero** [MayGo/tockler#90]
I followed the instructions for starting the development after git clone but when i run `npm start` the compiler throws this error

./src/index.ts
  Line 24:20:  Parsing error: '>' expected

I am using Windows 10 and node 13.7

**Comment by ammarNero** [comment]
This error is fixed now I think by changing .ts files to .tsx but now I am facing this error 
```
TypeScript error in D:/tockler/client/node_modules/antd-theme/lib/parser.ts(2,22):
Could not find a declaration file for module './runtime'. 'D:/tockler/client/node_modules/antd-theme/lib/runtime.js' implicitly has an 'any' type.  TS7016

    1 | /* eslint-disable max-classes-per-file */
  > 2 | import { tree } from './runtime';
      |                      ^
    3 |
    4 | const whitespaceRegexp = /^\s+/;
    5 | const dimensionRegexp = /^([+-]?\d*\.?\d+)(%|[a-z_]+)?/;
```

**Comment by MayGo** [comment]
I tried running it myself. I get the same error. It worked when I added the latest changes. I think the only thing that changed in my machine was Node version.
Sadly I don't have time to debug that.
But If you get a solution, let me know also. I would appreciate it a lot.

**Comment by ammarNero** [comment]
I actually just fixed it by adding `"noImplicitAny": false` to tsconfig.json in the client folder and it worked.
You can close this issue now if you want.

**Comment by MayGo** [comment]
thanks
