### ISSUE TITLE
[feature request] Edit Log Items

### ISSUE THREAD

**Issue by kown7** [MayGo/tockler#91]
It would be nice if the Log-Items could be edited. I'm always too late to start or turn them off.

**Comment by MayGo** [comment]
Will add!

**Comment by MayGo** [comment]
Added Log Item begin and end time editing. With time inputs and directly from timeline. 
![Edit log item](https://github.com/MayGo/tockler/raw/master/screenshots/editing-log-item.png 'Edit log item')

Also added New Log item form.
